import type { DashboardPayload, SourceStatus, Stock, Theme } from '../shared/types.ts';
import { indices, themeOrder, trackedStocks } from './themeConfig.ts';
import { lifecycle, normalizeTheme, scale } from './scoring.ts';

type Quote={symbol:string;last:number;changePct:number;amountYi:number;quoteTime:string};
type Bar=[string,string,string,string,string,string];
const n=(v:string|undefined)=>{const x=Number(v);return Number.isFinite(x)?x:0};
const round=(v:number,d=2)=>Number(v.toFixed(d));
function parseQuote(line:string):Quote|null{const m=line.match(/v_([^=]+)="([^"]*)"/);if(!m)return null;const p=m[2].split('~'),last=n(p[3]);if(!last)return null;return {symbol:m[1],last,changePct:n(p[32]),amountYi:round(n(p[37])/10000),quoteTime:p[30]||''}}
async function fetchQuotes(symbols:string[]){const r=await fetch(`https://qt.gtimg.cn/q=${symbols.join(',')}`,{signal:AbortSignal.timeout(10000),headers:{Referer:'https://gu.qq.com/'}});if(!r.ok)throw new Error(`腾讯行情 HTTP ${r.status}`);const text=new TextDecoder('gbk').decode(await r.arrayBuffer()),map=new Map<string,Quote>();for(const line of text.split(';')){const q=parseQuote(line);if(q)map.set(q.symbol,q)}if(map.size<3)throw new Error('腾讯行情返回记录不足');return map}
async function fetchBars(symbol:string):Promise<Bar[]>{const r=await fetch(`https://web.ifzq.gtimg.cn/appstock/app/fqkline/get?param=${symbol},day,,,12,qfq`,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`日线 HTTP ${r.status}`);const j=await r.json() as {data?:Record<string,{qfqday?:Bar[];day?:Bar[]}>};const x=j.data?.[symbol];return x?.qfqday||x?.day||[]}
async function mapLimit<T,R>(items:T[],limit:number,work:(x:T)=>Promise<R>){const out=new Array<R>(items.length);let cursor=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(cursor<items.length){const i=cursor++;out[i]=await work(items[i])}}));return out}
const priceLimit=(code:string)=>code.startsWith('30')||code.startsWith('68')?20:10;

export async function loadRealDashboard():Promise<DashboardPayload>{
  const symbols=[...indices.map(i=>i.symbol),...trackedStocks.map(s=>s.symbol)],quotes=await fetchQuotes(symbols);
  const barPairs=await mapLimit(trackedStocks,6,async s=>[s.symbol,await fetchBars(s.symbol)] as const),bars=new Map(barPairs);
  const times=[...quotes.values()].map(q=>q.quoteTime).filter(Boolean).sort(),latest=times.at(-1)||null;
  const asOf=latest?`${latest.slice(0,4)}-${latest.slice(4,6)}-${latest.slice(6,8)}T${latest.slice(8,10)}:${latest.slice(10,12)}:${latest.slice(12,14)}+08:00`:null;
  const tradeDate=latest?`${latest.slice(0,4)}-${latest.slice(4,6)}-${latest.slice(6,8)}`:null;
  const stocks:Stock[]=trackedStocks.flatMap(c=>{const q=quotes.get(c.symbol);if(!q)return [];const closes=(bars.get(c.symbol)||[]).map(b=>n(b[2])).filter(Boolean),base=closes.length>=6?closes.at(-6)!:closes[0],five=base?round((q.last/base-1)*100):null;const score=Math.min(100,scale(Math.log10(Math.max(q.amountYi,1)),0,2.3,45)+scale((five??0)+q.changePct,-12,20,35)+20);return [{code:c.code,name:c.name,theme:c.theme,role:c.role,last:q.last,changePct:q.changePct,fiveDayPct:five,amountYi:q.amountYi,quoteTime:asOf,score,reason:`腾讯行情：成交 ${q.amountYi} 亿元，5日 ${five===null?'未取得':`${five}%`}`}];});
  const themes:Theme[]=themeOrder.map((name,id)=>{const m=stocks.filter(s=>s.theme===name),day=round(m.reduce((a,s)=>a+s.changePct,0)/m.length),fs=m.flatMap(s=>s.fiveDayPct===null?[]:[s.fiveDayPct]),five=round(fs.reduce((a,v)=>a+v,0)/Math.max(fs.length,1)),breadth=m.filter(s=>s.changePct>0).length/m.length,amount=m.reduce((a,s)=>a+(s.amountYi||0),0),leader=[...m].sort((a,b)=>b.changePct-a.changePct)[0],capacity=[...m].sort((a,b)=>(b.amountYi||0)-(a.amountYi||0))[0],dims={capital:scale(Math.log10(Math.max(amount,1)),.5,2.7,30),profit:scale(day,-3,4,25),core:scale(Math.max(...m.map(s=>s.changePct)),-2,8,20),persistence:scale(five,-8,12,15),catalyst:0};return normalizeTheme({id:`theme-${id}`,name,score:0,bucket:'past',lifecycle:lifecycle(day,five,breadth),dayPct:day,fiveDayPct:five,completeness:90,dimensions:dims,leader:leader?.name||'未取得',capacityCore:capacity?.name||'未取得',trigger:'观察池广度与容量核心价格同步增强',invalidation:'容量核心转弱且观察池上涨比例低于三成',constituentCount:m.length,sourceNote:'腾讯行情固定观察池统计，非交易所官方行业指数；催化数据未接入且不按0计分。'});}).sort((a,b)=>b.score-a.score);
  const pool=stocks.length,up=stocks.filter(s=>s.changePct>0).length,down=stocks.filter(s=>s.changePct<0).length,lu=stocks.filter(s=>s.changePct>=priceLimit(s.code)-.15).length,ld=stocks.filter(s=>s.changePct<=-priceLimit(s.code)+.15).length;
  const iq=indices.map(i=>{const q=quotes.get(i.symbol);return {name:i.name,code:i.code,last:q?.last??null,changePct:q?.changePct??null}}),turnover=indices.slice(0,2).reduce((a,i)=>a+(quotes.get(i.symbol)?.amountYi||0),0),changes=iq.flatMap(i=>i.changePct===null?[]:[i.changePct]),avg=changes.reduce((a,v)=>a+v,0)/Math.max(changes.length,1),risk=Math.round(Math.max(0,Math.min(100,50+avg*8+(up-down)/Math.max(pool,1)*25)));
  const source:SourceStatus={provider:'腾讯证券行情',dataset:'指数/个股快照与前复权日线',state:'real',asOf,message:'公开行情接口；交易日盘中约30秒刷新，非Level-2'},scope=`${pool}只固定观察池（6个主题，每主题4只）；涨跌与涨跌停数量不是全A股统计`;
  return {market:{asOf,tradeDate,mode:'real',stale:false,completeness:90,scope,indices:iq,turnoverYi:{value:round(turnover),state:'real',source:'腾讯证券行情-沪深指数成交额'},advances:{value:up,state:'real',source:'固定观察池'},declines:{value:down,state:'real',source:'固定观察池'},limitUp:{value:lu,state:'estimated',source:'固定观察池按板块阈值识别'},limitDown:{value:ld,state:'estimated',source:'固定观察池按板块阈值识别'},breakRate:{value:null,state:'unavailable',source:'尚未接入官方涨停池'},riskAppetite:risk,sources:[source]},themes,stocks:stocks.sort((a,b)=>b.score-a.score),positions:[{code:'待录入',name:'尚未连接持仓',theme:'未绑定',quantity:0,cost:null,last:null,state:'等待用户录入',reviewTrigger:'录入真实数量、成本与信用账户担保比例后评估'}],dailyReview:{tradeDate,title:`${tradeDate||'最近交易日'}复盘`,scope,advances:up,declines:down,limitUp:lu,limitDown:ld,topThemes:themes.slice(0,3).map(t=>({name:t.name,dayPct:t.dayPct,score:t.score})),notes:[`行情时间：${asOf||'未取得'}`,`观察池上涨 ${up} 家、下跌 ${down} 家。`,'催化、龙虎榜、融资融券和全市场炸板率尚未接入，保持“未取得”。']}};
}

export function unavailableDashboard(message:string,last?:DashboardPayload):DashboardPayload{
  if(last)return {...last,market:{...last.market,stale:true,sources:[...last.market.sources,{provider:'腾讯证券行情',dataset:'刷新',state:'unavailable',asOf:new Date().toISOString(),message}]}};
  const field={value:null,state:'unavailable' as const,source:'未取得'};
  return {market:{asOf:null,tradeDate:null,mode:'unavailable',stale:true,completeness:0,scope:'真实行情尚未取得',indices:indices.map(i=>({name:i.name,code:i.code,last:null,changePct:null})),turnoverYi:field,advances:field,declines:field,limitUp:field,limitDown:field,breakRate:field,riskAppetite:null,sources:[{provider:'腾讯证券行情',dataset:'初始化',state:'unavailable',asOf:new Date().toISOString(),message}]},themes:[],stocks:[],positions:[],dailyReview:{tradeDate:null,title:'最近交易日复盘',scope:'真实行情尚未取得',advances:null,declines:null,limitUp:null,limitDown:null,topThemes:[],notes:[message]}};
}
