import { useMemo, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import type { DashboardPayload, Stock } from '../shared/types';
import type { Holding, NextDayAlert, WatchItem } from './useLocalWorkspace';

const pct=(n:number|null)=>n===null?'未取得':`${n>0?'+':''}${n.toFixed(2)}%`;
const money=(n:number|null)=>n===null?'—':`¥${n.toFixed(2)}`;
const tone=(n:number|null)=>n===null?'':n>=0?'up':'down';

function AddStock({stocks,label,onAdd,withPosition=false}:{stocks:Stock[];label:string;onAdd:(code:string,quantity:number,cost:number|null,note:string)=>void;withPosition?:boolean}){
  const [code,setCode]=useState(stocks[0]?.code||''),[quantity,setQuantity]=useState(''),[cost,setCost]=useState(''),[note,setNote]=useState('');
  const submit=()=>{const qty=withPosition?Number(quantity):0;if(!code||(withPosition&&(!Number.isFinite(qty)||qty<=0)))return;const parsedCost=cost===''?null:Number(cost);onAdd(code,qty,Number.isFinite(parsedCost)?parsedCost:null,note.trim());setQuantity('');setCost('');setNote('')};
  return <div className="entry-form"><select aria-label="选择股票" value={code} onChange={event=>setCode(event.target.value)}>{stocks.map(stock=><option key={stock.code} value={stock.code}>{stock.code} {stock.name} · {stock.theme}</option>)}</select>{withPosition?<><input aria-label="持仓数量" inputMode="numeric" placeholder="持仓数量" value={quantity} onChange={event=>setQuantity(event.target.value)}/><input aria-label="成本价" inputMode="decimal" placeholder="成本价（可空）" value={cost} onChange={event=>setCost(event.target.value)}/><input aria-label="持仓备注" placeholder="备注（可空）" value={note} onChange={event=>setNote(event.target.value)}/></>:null}<button onClick={submit}><Plus size={15}/>{label}</button></div>
}

export function HoldingsPanel({data,holdings,onAdd,onRemove}:{data:DashboardPayload;holdings:Holding[];onAdd:(code:string,quantity:number,cost:number|null,note:string)=>void;onRemove:(code:string)=>void}){
  const rows=holdings.flatMap(holding=>{const stock=data.stocks.find(item=>item.code===holding.code);return stock?[{holding,stock}]:[]});
  const marketValue=rows.reduce((sum,row)=>sum+(row.stock.last??0)*row.holding.quantity,0),costValue=rows.reduce((sum,row)=>sum+(row.holding.cost??row.stock.last??0)*row.holding.quantity,0),pnl=costValue?marketValue-costValue:null;
  return <section className="feature-panel workspace-panel"><header><div><h2>我的持仓</h2><p>手动录入并仅保存在当前浏览器，不连接券商、不执行交易</p></div><span className="neutral-badge">本机保存</span></header><AddStock stocks={data.stocks} label="添加持仓" withPosition onAdd={onAdd}/><div className="account-summary"><span>持仓市值 <b>{money(marketValue)}</b></span><span>参考盈亏 <b className={tone(pnl)}>{pnl===null?'成本未完整录入':money(pnl)}</b></span><span>持仓数 <b>{rows.length}</b></span></div>{rows.length?<div className="workspace-list">{rows.map(({holding,stock})=>{const profit=holding.cost&&stock.last?(stock.last/holding.cost-1)*100:null;return <article key={holding.code}><div><b>{stock.name}</b><small>{stock.code} · {stock.theme} · {stock.role}</small></div><span>数量<b>{holding.quantity}</b></span><span>成本<b>{money(holding.cost)}</b></span><span>现价<b>{money(stock.last)}</b></span><span>盈亏<b className={tone(profit)}>{pct(profit)}</b></span><span>{holding.note||'无备注'}</span><button aria-label={`删除${stock.name}持仓`} onClick={()=>onRemove(stock.code)}><Trash2 size={15}/></button></article>})}</div>:<div className="empty-state">尚未添加持仓。请从上方选择股票，填写数量后点击“添加持仓”。</div>}</section>
}

export function WatchlistPanel({data,watchlist,onAdd,onRemove}:{data:DashboardPayload;watchlist:WatchItem[];onAdd:(code:string)=>void;onRemove:(code:string)=>void}){
  const rows=watchlist.flatMap(item=>{const stock=data.stocks.find(candidate=>candidate.code===item.code);return stock?[stock]:[]});
  return <section className="feature-panel workspace-panel"><header><div><h2>我的自选</h2><p>从当前24只真实行情观察池中添加，自选只保存在当前浏览器</p></div><span className="neutral-badge">{rows.length}只</span></header><AddStock stocks={data.stocks} label="加入自选" onAdd={code=>onAdd(code)}/>{rows.length?<div className="workspace-list watch-list">{rows.map(stock=><article key={stock.code}><div><b>{stock.name}</b><small>{stock.code} · {stock.theme} · {stock.role}</small></div><span>现价<b>{money(stock.last)}</b></span><span>今日<b className={tone(stock.changePct)}>{pct(stock.changePct)}</b></span><span>5日<b className={tone(stock.fiveDayPct)}>{pct(stock.fiveDayPct)}</b></span><span>20日<b className={tone(stock.twentyDayPct)}>{pct(stock.twentyDayPct)}</b></span><span>评分<b>{stock.score}</b></span><button aria-label={`删除${stock.name}自选`} onClick={()=>onRemove(stock.code)}><Trash2 size={15}/></button></article>)}</div>:<div className="empty-state">尚未添加自选股。请从上方选择后点击“加入自选”。</div>}</section>
}

export function AlertsPanel({alerts,onStatus}:{alerts:NextDayAlert[];onStatus:(id:string,status:NextDayAlert['status'])=>void}){
  const rows=[...alerts].sort((a,b)=>b.targetDate.localeCompare(a.targetDate));
  return <section className="feature-panel alert-panel"><header><div><h2>盘中预警 / 次日观察</h2><p>来自每日复盘的验证条件；系统不盯盘下单，需人工确认触发状态</p></div><span className="neutral-badge">{rows.filter(item=>item.status==='观察中').length}条观察中</span></header>{rows.length?<div className="alert-list">{rows.map(item=><article key={item.id}><div className="alert-title"><time>{item.targetDate}</time><b>{item.theme}</b><span>{item.stock}</span><select aria-label={`${item.theme}状态`} value={item.status} onChange={event=>onStatus(item.id,event.target.value as NextDayAlert['status'])}><option>观察中</option><option>已触发</option><option>已失效</option></select></div><p><b>确认触发：</b>{item.trigger}</p><p><b>失效条件：</b>{item.invalidation}</p><small>由 {item.sourceReviewDate} 复盘生成 · 仅为观察计划，不是交易指令</small></article>)}</div>:<div className="empty-state">还没有次日观察。进入“每日复盘”，点击“完成复盘并生成次日观察”。</div>}</section>
}

export function DailyReviewPanel({data,onGenerate}:{data:DashboardPayload;onGenerate:()=>number}){
  const [message,setMessage]=useState('');
  return <section className="feature-panel"><header><div><h2>每日复盘（V2）</h2><p>{data.dailyReview.scope}。先确认市场生态，再看20日主线与3日温度；产业事实请在“价值投机V2”录入。</p></div><button className="primary-action" onClick={()=>{const count=onGenerate();setMessage(count?`已生成 ${count} 条次日观察，可到“盘中预警”查看。`:'行情日期未取得，暂不能生成。')}}>完成复盘并生成次日观察</button></header>{message?<div className="success-note">{message}</div>:null}<div className="analysis-grid"><article><span>观察池涨跌</span><b>{data.dailyReview.advances??'—'} / {data.dailyReview.declines??'—'}</b><p>上涨家数 / 下跌家数</p></article><article><span>观察池涨跌停</span><b>{data.dailyReview.limitUp??'—'} / {data.dailyReview.limitDown??'—'}</b><p>按股票板块涨跌幅阈值估算</p></article><article><span>当日强度前三</span><b>{data.dailyReview.topThemes.map(item=>item.name).join('、')||'未取得'}</b><p>{data.dailyReview.topThemes.map(item=>`${item.name} ${pct(item.dayPct)}`).join('；')}</p></article><article><span>复盘纪律</span><b>先事实，后判断</b><p>产业证据、触发条件、失效条件均不能缺省。</p></article></div></section>
}

export function BacktestPanel({data}:{data:DashboardPayload}){
  const usable=data.stocks.filter(stock=>stock.twentyDayPct!==null&&stock.maxDrawdown20Pct!==null),avg=(key:'fiveDayPct'|'twentyDayPct'|'maxDrawdown20Pct')=>usable.length?usable.reduce((sum,stock)=>sum+(stock[key]??0),0)/usable.length:null,winRate=usable.length?usable.filter(stock=>(stock.twentyDayPct??0)>0).length/usable.length*100:null;
  const byTheme=useMemo(()=>data.themes.map(theme=>{const rows=usable.filter(stock=>stock.theme===theme.name);return {name:theme.name,count:rows.length,return20:rows.length?rows.reduce((sum,stock)=>sum+(stock.twentyDayPct??0),0)/rows.length:null,drawdown:rows.length?rows.reduce((sum,stock)=>sum+(stock.maxDrawdown20Pct??0),0)/rows.length:null}}).sort((a,b)=>(b.return20??-Infinity)-(a.return20??-Infinity)),[data.themes,usable]);
  return <section className="feature-panel backtest-panel"><header><div><h2>历史回看</h2><p>使用当前固定观察池的前复权日线，展示近5/20交易日表现</p></div><span className="neutral-badge">不是策略收益回测</span></header><div className="metric-cards"><article><span>观察池近5日均值</span><b className={tone(avg('fiveDayPct'))}>{pct(avg('fiveDayPct'))}</b></article><article><span>观察池近20日均值</span><b className={tone(avg('twentyDayPct'))}>{pct(avg('twentyDayPct'))}</b></article><article><span>20日上涨比例</span><b>{pct(winRate)}</b></article><article><span>20日平均最大回撤</span><b className="down">{pct(avg('maxDrawdown20Pct'))}</b></article></div><div className="module-table history-table"><div className="module-table-head"><span>主题</span><span>样本</span><span>近20日均值</span><span>平均最大回撤</span></div>{byTheme.map(row=><div className="module-table-row" key={row.name}><b>{row.name}</b><span>{row.count}只</span><span className={tone(row.return20)}>{pct(row.return20)}</span><span className="down">{pct(row.drawdown)}</span></div>)}</div><p className="module-boundary neutral-boundary">边界：这是“当前观察池回看”，存在幸存者偏差，不代表按历史时点评分选股的真实策略回测。后续接入每日评分快照后，才能计算无未来函数的胜率和净值曲线。</p></section>
}

export function MonthlyCandidatesPanel({data,onWatch}:{data:DashboardPayload;onWatch:(code:string)=>void}){
  const candidates=[...data.stocks].filter(stock=>stock.twentyDayPct!==null).sort((a,b)=>(b.score+(b.twentyDayPct??0))-(a.score+(a.twentyDayPct??0))).slice(0,10);
  return <section className="feature-panel workspace-panel"><header><div><h2>月度候选</h2><p>按当前评分与近20日趋势排序，每次行情刷新后自动更新</p></div><span className="neutral-badge">候选不等于买入许可</span></header><div className="workspace-list watch-list candidates-list">{candidates.map((stock,index)=><article key={stock.code}><strong>{index+1}</strong><div><b>{stock.name}</b><small>{stock.code} · {stock.theme} · {stock.role}</small></div><span>评分<b>{stock.score}</b></span><span>今日<b className={tone(stock.changePct)}>{pct(stock.changePct)}</b></span><span>20日<b className={tone(stock.twentyDayPct)}>{pct(stock.twentyDayPct)}</b></span><span>最大回撤<b className="down">{pct(stock.maxDrawdown20Pct)}</b></span><button onClick={()=>onWatch(stock.code)}><Plus size={14}/>自选</button></article>)}</div><p className="module-boundary neutral-boundary">筛选只是研究排序。是否可参与仍需结合生命周期、触发条件、账户风险和次日价格验证。</p></section>
}
